# mongodb单机
services:
  mongo:
    image: mongo:7.0.12 # mongo:latest
    container_name: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=demo123
    volumes:
      - /data/db/mongo_data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    ports:
      - 27017:27017
    networks:
      - app-network

volumes:
  mongo_data:

networks:
  app-network:
